### ISSUE TITLE
Unable to create a controlledTerms schema 

### ISSUE THREAD

**Issue by arnaumanasanch** [HumanBrainProject/openMINDS_generator#11]
As it is easily done with core schemas through the command `mycollection.add_core_protocol` for example,  I am missing the functionality to do the same with controlledTerms schemas, something such as `mycollection.add_controlledTerms_species`. There are some core schemas that require as argument a controlledTerms schema.

**Comment by lzehl** [comment]
@arnaumanasanch did the latest update of the Python API solve this issue?

**Comment by arnaumanasanch** [comment]
Yes, absolutely. Now it works fine.
