### ISSUE TITLE
extension of concept schemas not working in all cases

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_generator#32]
It seems that the pipeline is not extending the schemas properly in the cases where the concept schema is located in a different openMINDS repo. 

Example: 
https://github.com/HumanBrainProject/openMINDS_core/blob/v4/schemas/products/device.schema.tpl.json
-> this is the concept schema for all devices, but the Electrode (device) schema:
https://github.com/HumanBrainProject/openMINDS/blob/documentation/v3/ephys/v1/device/electrode.schema.json
-> does not actually extend the core/device concept schema as it should according to the syntax definitions:
https://github.com/HumanBrainProject/openMINDS_ephys/blob/v1/schemas/device/electrode.schema.tpl.json

@olinux @skoehnen @apdavison Did we miss anything? is this a version reference issue?

**Comment by apdavison** [comment]
For the example you gave, there was a typo in the schema template ("Device" where it should have been "device"), which I fixed here [c5e20b429dc181dc95406144ca4f1c69cfd8e4b3].

Did that solve the problem? Are there other examples of failure to extend properly?

**Comment by lzehl** [comment]
I hope the rest is fine. I saw that you spotted the error. Thanks. Let's close this. If I spot another one I can reopen the issue
